# Dockerfile.admin
FROM python:3.11-slim

WORKDIR /app

# Instalar dependências
COPY admin/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY admin/ .

# Expor porta
EXPOSE 5000

# Executar aplicação
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:create_app()"]